pkgname = "orm"
output = "internal/common/orm"
wipe = true
no-tests = true
add-global-variants = true
add-enum-types = true
no-context = true
add-soft-deletes = true

# sqlboiler psql --add-soft-deletes
[psql]
dbname = "saas"
host = "127.0.0.1"
port = 15542
user = "postgres"
pass = "lirous587"
schema = "public"
sslmode = "disable"
# 启用自动时间戳
auto-timestamps = true
updated-at-column = "updated_at"
created-at-column = "created_at"
# blacklist = ["migrations"] # 根据需要添加黑名单表


[aliases.tables.apis]
up_plural = "Apis"   # 结构体切片类型名
up_singular = "Api"    # 结构体类型名
down_plural = "apis"   # 变量/方法名复数
down_singular = "api"    # 变量/方法名单数


# 将数据库 decimal/numeric 类型映射到 shopspring/decimal.Decimal
[[types]]
  [types.match]
    db_type = "decimal"  # 匹配数据库的 decimal 类型

  [types.replace]
    type = "decimal.Decimal"  # 替换为 shopspring/decimal.Decimal

  [types.imports]
    third_party = ['"github.com/shopspring/decimal"']

[[types]]
  [types.match]
    db_type = "numeric"  # 匹配数据库的 numeric 类型 (PostgreSQL 中 numeric 等价于 decimal)

  [types.replace]
    type = "decimal.Decimal"

  [types.imports]
    third_party = ['"github.com/shopspring/decimal"']